const Text = {
    baseStyle: {
        fontFamily: 'Inter',
        fontStyle: 'normal',
        color: '#667080',
    },
    variants: {
        formlabel: {
            p: 0,
            minW: '77px',
            maxW: '77px',
            fontSize: '0.875rem',
            lineHeight: '100%',
            fontStyle: 'normal',
            fontWeight: '400',
            color: '#667080',
            wordBreak: 'keep-all',
            overflowWrap: 'break-word',
        },
        formpartTitle: {
            p: 0,
            fontSize: '0.875rem',
            lineHeight: '20px',
            fontStyle: 'normal',
            fontWeight: '600',
            color: '#667080',
        },
        pageTitle: {
            p: 0,
            fontStyle: 'normal',
            fontWeight: '400',
            fontSize: '2.25rem',
            lineHeight: '2.75rem',
            color: '#667080',
            wordBreak: 'keep-all',
            overflowWrap: 'break-word',
        },
        searchResult: {
            fontStyle: 'normal',
            fontWeight: '400',
            fontSize: '14px',
            lineHeight: '20px',
            color: '#667080',
        },
        pageSiteName: {
            fontWeight: 500,
            fontSize: '14px',
            lineHeight: '20px',
            position: 'absolute',
            top: '20px',
            right: '42px',
            zIndex: 99,
        },
        w400s14: {
            fontStyle: 'normal',
            fontWeight: '400',
            fontSize: '0.875rem',
            lineHeight: '1.25rem',
            color: '#667080',
        },
        w500s14: {
            fontStyle: 'normal',
            fontWeight: 500,
            fontSize: '0.875rem',
            lineHeight: '1.25rem',
            color: '#667080',
        },
        w400s12: {
            fontStyle: 'normal',
            fontWeight: '400',
            fontSize: '0.75rem',
            lineHeight: '1.25rem',
            color: '#667080',
        },
        w700s16: {
            fontStyle: 'normal',
            fontWeight: '700',
            fontSize: '1rem',
            lineHeight: '1.5rem',
            color: '#667080',
        },
        dashboardList: {
            fontStyle: 'normal',
            fontWeight: '400',
            fontSize: '0.875rem',
            lineHeight: '1.25rem',
            color: '#667080',
            paddingTop: '7.5px',
            paddingBottom: '7.5px',
        },
    },
};

export default Text;
