version: "3.5"

services:
  frontend:
    image: nginx:1.23-alpine
    container_name: mic-iem-frontend
    ports:
      - ${PORT}:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./build:/var/www/html

