export interface humanInfoValues {
    aCertificationDate: Date | string | undefined;
    accidentInsuranceAmountOne: Number | string | undefined;
    accidentInsuranceCompanyNameOne: String | undefined;
    accidentInsuranceEndOne: Date | string | undefined;
    accidentInsuranceSignDateOne: Date | string | undefined;
    accidentInsuranceStartOne: Date | string | undefined;
    accidentInsuranceAmountTwo: Number | string | undefined;
    accidentInsuranceCompanyNameTwo: String | undefined;
    accidentInsuranceEndTwo: Date | string | undefined;
    accidentInsuranceSignDateTwo: Date | string | undefined;
    accidentInsuranceStartTwo: Date | string | undefined;
    accidentInsuranceAmountThree: Number | string | undefined;
    accidentInsuranceCompanyNameThree: String | undefined;
    accidentInsuranceEndThree: Date | string | undefined;
    accidentInsuranceSignDateThree: Date | string | undefined;
    accidentInsuranceStartThree: Date | string | undefined;
    address: String | undefined;
    birthday: Date | string | undefined;
    bloodType: String | undefined;
    cCertificationDate: Date | string | undefined;
    certificationIssue: Date | string | undefined;
    certificationName: String | undefined;
    certificationWithdraw: Date | string | undefined;
    contractingCompanyName: String | undefined;
    emergencyTel: String | undefined;
    exCertificationDate: Date | string | undefined;
    gender: String | undefined;
    hCertificationDate: Date | string | undefined;
    hazardNotifyDate: Date | string | undefined;
    idno: String | undefined;
    lCertificationDate: Date | string | undefined;
    laborAssociationDate: Date | string | undefined;
    laborInsuranceApplyDate: Date | string | undefined;
    liaison: String | undefined;
    name: String | undefined;
    o2CertificationDate: Date | string | undefined;
    osCertificationDate: Date | string | undefined;
    sCertificationDate: Date | string | undefined;
    saCertificationDate: Date | string | undefined;
    safetyHealthyEducationIssue: Date | string | undefined;
    safetyHealthyEducationWithdraw: Date | string | undefined;
    supplierIndustrialSafetyNumber: String | undefined;
    tel: String | undefined;
    viceContractingCompanyName: String | undefined;
    wahCertificationDate: Date | string | undefined;
}

export interface formValues extends humanInfoValues {
    sixStatus: string | undefined;
    certificationStatus: string | undefined;
    aStatus: string | undefined;
    wahStatus: string | undefined;
    lStatus: string | undefined;
    cStatus: string | undefined;
    hStatus: string | undefined;
    exStatus: string | undefined;
    sStatus: string | undefined;
    saStatus: string | undefined;
    osStatus: string | undefined;
    o2Status: string | undefined;
}

export interface formFiles {
    F6Img?: File;
    G1Img?: File;
    G2Img?: File;
    G3Img?: File;
    HImgs: (File | undefined)[];
    IDFImg?: File;
    IDRImg?: File;
    LImg?: File;
    PImg?: File;
    R6Img?: File;
    MAFImg?: File;
    MARImg?: File;
    AFImg?: File;
    ARImg?: File;
    WAHFImg?: File;
    WAHRImg?: File;
    LFImg?: File;
    LRImg?: File;
    CFImg?: File;
    CRImg?: File;
    HFImg?: File;
    HRImg?: File;
    EXFImg?: File;
    EXRImg?: File;
    SFImg?: File;
    SRImg?: File;
    SAFImg?: File;
    SARImg?: File;
    OSFImg?: File;
    OSRImg?: File;
    O2FImg?: File;
    O2RImg?: File;
}

export interface humanTableValues {
    name: string;
    gender: string | null;
    birthday: string | null;
    bloodType: string | null;
    tel: string | null;
    liaison: string | null;
    emergencyTel: string | null;
    address: string | null;
    hazardNotifyDate: string | null;
    supplierIndustrialSafetyNumber: string | null;
    safetyHealthyEducationIssue: string | null;
    safetyHealthyEducationWithdraw: string | null;
    laborInsuranceApplyDate: string | null;
    laborAssociationDate: string | null;
    certificationName: string | null;
    accidentInsuranceStartOne: string | null;
    accidentInsuranceStartTwo: string | null;
    accidentInsuranceStartThree: string | null;
    accidentInsuranceEndOne: string | null;
    accidentInsuranceEndTwo: string | null;
    accidentInsuranceEndThree: string | null;
    accidentInsuranceAmountOne: string | null;
    accidentInsuranceAmountTwo: string | null;
    accidentInsuranceAmountThree: string | null;
    accidentInsuranceSignDateOne: string | null;
    accidentInsuranceSignDateTwo: string | null;
    accidentInsuranceSignDateThree: string | null;
    accidentInsuranceCompanyNameOne: string | null;
    accidentInsuranceCompanyNameTwo: string | null;
    accidentInsuranceCompanyNameThree: string | null;
    contractingCompanyName: string | null;
    viceContractingCompanyName: string | null;
    aCertificationDate: string | null;
    boshCertificationDate: string | null;
    aosCertificationDate: string | null;
    aohCertificationDate: string | null;
    frCertificationDate: string | null;
    o2CertificationDate: string | null;
    osCertificationDate: string | null;
    saCertificationDate: string | null;
    sCertificationDate: string | null;
    ssaCertificationDate: string | null;
    maCertificationDate: string | null;
    rCertificationDate: string | null;
    fsCertificationDate: string | null;
    peCertificationDate: string | null;
    rsCertificationDate: string | null;
    dwCertificationDate: string | null;
    aWithdrawDate: string | null;
    boshWithdrawDate: string | null;
    aosWithdrawDate: string | null;
    aohWithdrawDate: string | null;
    frWithdrawDate: string | null;
    o2WithdrawDate: string | null;
    osWithdrawDate: string | null;
    saWithdrawDate: string | null;
    sWithdrawDate: string | null;
    maWithdrawDate: string | null;
    rWithdrawDate: string | null;
    ssaWithdrawDate: string | null;
    fsWithdrawDate: string | null;
    peWithdrawDate: string | null;
    rsWithdrawDate: string | null;
    dwWithdrawDate: string | null;
    reviewStaff: string | null;
    idno: string;
    sixStatus: string | null;
    certificationStatus: string | null;
    aStatus: string | null;
    boshStatus: string | null;
    aosStatus: string | null;
    aohStatus: string | null;
    frStatus: string | null;
    o2Status: string | null;
    osStatus: string | null;
    saStatus: string | null;
    sStatus: string | null;
    maStatus: string | null;
    rStatus: string | null;
    ssaStatus: string | null;
    fsStatus: string | null;
    peStatus: string | null;
    rsStatus: string | null;
    dwStatus: string | null;
    no: string | null;
}

export interface ISelectedHuman {
    no: string | null;
    idno: string;
    name: string;
}
