import { IEHSForm, IEHSFormTargetInItem } from './Common';

export interface IEHSFormNormal extends IEHSForm {
    AA01Normal: boolean | null;
    AA02Normal: boolean | null;
    AA03Normal: boolean | null;
    AA04Normal: boolean | null;
    AA05Normal: boolean | null;
    AA06Normal: boolean | null;
    AA07Normal: boolean | null;
    AA08Normal: boolean | null;
    AA09Normal: boolean | null;
    AA10Normal: boolean | null;
    AA11Normal: boolean | null;
    AA12Normal: boolean | null;
    AA13Normal: boolean | null;
    AA14Normal: boolean | null;
    AA15Normal: boolean | null;
    AA16Normal: boolean | null;
    AA17Normal: boolean | null;
    AA18Normal: boolean | null;
    AA19Normal: boolean | null;
    AA20Normal: boolean | null;
    AA21Normal: boolean | null;
    AA22Normal: boolean | null;
    AB01Normal: boolean | null;
    AB02Normal: boolean | null;
    AB03Normal: boolean | null;
    AB04Normal: boolean | null;
    AB05Normal: boolean | null;
    AB06Normal: boolean | null;
    AC01Normal: boolean | null;
    AC02Normal: boolean | null;
    AC03Normal: boolean | null;
    AD01Normal: boolean | null;
    AD02Normal: boolean | null;
    AD03Normal: boolean | null;
    AD04Normal: boolean | null;
    AD05Normal: boolean | null;
    AD06Normal: boolean | null;
    AD07Normal: boolean | null;
    AD08Normal: boolean | null;
    AE01Normal: boolean | null;
    AE02Normal: boolean | null;
    AE03Normal: boolean | null;
    AE04Normal: boolean | null;
    AE05Normal: boolean | null;
    AE06Normal: boolean | null;
    AE07Normal: boolean | null;
    AF01Normal: boolean | null;
    AF02Normal: boolean | null;
    AF03Normal: boolean | null;
    AF04Normal: boolean | null;

    AA01Misfit: boolean | null;
    AA02Misfit: boolean | null;
    AA03Misfit: boolean | null;
    AA04Misfit: boolean | null;
    AA05Misfit: boolean | null;
    AA06Misfit: boolean | null;
    AA07Misfit: boolean | null;
    AA08Misfit: boolean | null;
    AA09Misfit: boolean | null;
    AA10Misfit: boolean | null;
    AA11Misfit: boolean | null;
    AA12Misfit: boolean | null;
    AA13Misfit: boolean | null;
    AA14Misfit: boolean | null;
    AA15Misfit: boolean | null;
    AA16Misfit: boolean | null;
    AA17Misfit: boolean | null;
    AA18Misfit: boolean | null;
    AA19Misfit: boolean | null;
    AA20Misfit: boolean | null;
    AA21Misfit: boolean | null;
    AA22Misfit: boolean | null;
    AB01Misfit: boolean | null;
    AB02Misfit: boolean | null;
    AB03Misfit: boolean | null;
    AB04Misfit: boolean | null;
    AB05Misfit: boolean | null;
    AB06Misfit: boolean | null;
    AC01Misfit: boolean | null;
    AC02Misfit: boolean | null;
    AC03Misfit: boolean | null;
    AD01Misfit: boolean | null;
    AD02Misfit: boolean | null;
    AD03Misfit: boolean | null;
    AD04Misfit: boolean | null;
    AD05Misfit: boolean | null;
    AD06Misfit: boolean | null;
    AD07Misfit: boolean | null;
    AD08Misfit: boolean | null;
    AE01Misfit: boolean | null;
    AE02Misfit: boolean | null;
    AE03Misfit: boolean | null;
    AE04Misfit: boolean | null;
    AE05Misfit: boolean | null;
    AE06Misfit: boolean | null;
    AE07Misfit: boolean | null;
    AF01Misfit: boolean | null;
    AF02Misfit: boolean | null;
    AF03Misfit: boolean | null;
    AF04Misfit: boolean | null;

    AA01Ameliorate: IEHSFormTargetInItem[];
    AA02Ameliorate: IEHSFormTargetInItem[];
    AA03Ameliorate: IEHSFormTargetInItem[];
    AA04Ameliorate: IEHSFormTargetInItem[];
    AA05Ameliorate: IEHSFormTargetInItem[];
    AA06Ameliorate: IEHSFormTargetInItem[];
    AA07Ameliorate: IEHSFormTargetInItem[];
    AA08Ameliorate: IEHSFormTargetInItem[];
    AA09Ameliorate: IEHSFormTargetInItem[];
    AA10Ameliorate: IEHSFormTargetInItem[];
    AA11Ameliorate: IEHSFormTargetInItem[];
    AA12Ameliorate: IEHSFormTargetInItem[];
    AA13Ameliorate: IEHSFormTargetInItem[];
    AA14Ameliorate: IEHSFormTargetInItem[];
    AA15Ameliorate: IEHSFormTargetInItem[];
    AA16Ameliorate: IEHSFormTargetInItem[];
    AA17Ameliorate: IEHSFormTargetInItem[];
    AA18Ameliorate: IEHSFormTargetInItem[];
    AA19Ameliorate: IEHSFormTargetInItem[];
    AA20Ameliorate: IEHSFormTargetInItem[];
    AA21Ameliorate: IEHSFormTargetInItem[];
    AA22Ameliorate: IEHSFormTargetInItem[];
    AB01Ameliorate: IEHSFormTargetInItem[];
    AB02Ameliorate: IEHSFormTargetInItem[];
    AB03Ameliorate: IEHSFormTargetInItem[];
    AB04Ameliorate: IEHSFormTargetInItem[];
    AB05Ameliorate: IEHSFormTargetInItem[];
    AB06Ameliorate: IEHSFormTargetInItem[];
    AC01Ameliorate: IEHSFormTargetInItem[];
    AC02Ameliorate: IEHSFormTargetInItem[];
    AC03Ameliorate: IEHSFormTargetInItem[];
    AD01Ameliorate: IEHSFormTargetInItem[];
    AD02Ameliorate: IEHSFormTargetInItem[];
    AD03Ameliorate: IEHSFormTargetInItem[];
    AD04Ameliorate: IEHSFormTargetInItem[];
    AD05Ameliorate: IEHSFormTargetInItem[];
    AD06Ameliorate: IEHSFormTargetInItem[];
    AD07Ameliorate: IEHSFormTargetInItem[];
    AD08Ameliorate: IEHSFormTargetInItem[];
    AE01Ameliorate: IEHSFormTargetInItem[];
    AE02Ameliorate: IEHSFormTargetInItem[];
    AE03Ameliorate: IEHSFormTargetInItem[];
    AE04Ameliorate: IEHSFormTargetInItem[];
    AE05Ameliorate: IEHSFormTargetInItem[];
    AE06Ameliorate: IEHSFormTargetInItem[];
    AE07Ameliorate: IEHSFormTargetInItem[];
    AF01Ameliorate: IEHSFormTargetInItem[];
    AF02Ameliorate: IEHSFormTargetInItem[];
    AF03Ameliorate: IEHSFormTargetInItem[];
    AF04Ameliorate: IEHSFormTargetInItem[];
}

export type NormalGroupKey = 'AA' | 'AB' | 'AC' | 'AD' | 'AE' | 'AF';
