import { IEHSForm, IEHSFormTargetInItem } from './Common';

export interface IEHSFormSpecial extends IEHSForm {
    BA01Normal: boolean | null;
    BA02Normal: boolean | null;
    BA03Normal: boolean | null;
    BA04Normal: boolean | null;
    BA05Normal: boolean | null;
    BA06Normal: boolean | null;
    BA07Normal: boolean | null;
    BA08Normal: boolean | null;
    BA09Normal: boolean | null;
    BB01Normal: boolean | null;
    BB02Normal: boolean | null;
    BB03Normal: boolean | null;
    BB04Normal: boolean | null;
    BB05Normal: boolean | null;
    BB06Normal: boolean | null;
    BB07Normal: boolean | null;
    BB08Normal: boolean | null;
    BB09Normal: boolean | null;
    BB10Normal: boolean | null;
    BB11Normal: boolean | null;
    BB12Normal: boolean | null;
    BB13Normal: boolean | null;
    BB14Normal: boolean | null;
    BB15Normal: boolean | null;
    BB16Normal: boolean | null;
    BB17Normal: boolean | null;
    BC01Normal: boolean | null;
    BC02Normal: boolean | null;
    BC03Normal: boolean | null;
    BC04Normal: boolean | null;
    BC05Normal: boolean | null;
    BC06Normal: boolean | null;
    BC07Normal: boolean | null;
    BC08Normal: boolean | null;
    BC09Normal: boolean | null;
    BC10Normal: boolean | null;
    BC11Normal: boolean | null;
    BD01Normal: boolean | null;
    BD02Normal: boolean | null;
    BD03Normal: boolean | null;
    BD04Normal: boolean | null;
    BD05Normal: boolean | null;
    BD06Normal: boolean | null;
    BD07Normal: boolean | null;
    BD08Normal: boolean | null;
    BD09Normal: boolean | null;
    BD10Normal: boolean | null;
    BD11Normal: boolean | null;
    BD12Normal: boolean | null;
    BD13Normal: boolean | null;
    BD14Normal: boolean | null;
    BD15Normal: boolean | null;
    BD16Normal: boolean | null;
    BE01Normal: boolean | null;
    BE02Normal: boolean | null;
    BE03Normal: boolean | null;
    BE04Normal: boolean | null;
    BF01Normal: boolean | null;
    BF02Normal: boolean | null;
    BF03Normal: boolean | null;
    BF04Normal: boolean | null;
    BF05Normal: boolean | null;
    BF06Normal: boolean | null;
    BF07Normal: boolean | null;
    BF08Normal: boolean | null;
    BF09Normal: boolean | null;
    BF10Normal: boolean | null;
    BF11Normal: boolean | null;
    BG01Normal: boolean | null;
    BG02Normal: boolean | null;
    BG03Normal: boolean | null;
    BG04Normal: boolean | null;
    BG05Normal: boolean | null;
    BG06Normal: boolean | null;
    BG07Normal: boolean | null;
    BH01Normal: boolean | null;
    BH02Normal: boolean | null;
    BH03Normal: boolean | null;
    BH04Normal: boolean | null;
    BI01Normal: boolean | null;
    BI02Normal: boolean | null;
    BI03Normal: boolean | null;
    BJ01Normal: boolean | null;
    BJ02Normal: boolean | null;
    BJ03Normal: boolean | null;
    BJ04Normal: boolean | null;
    BJ05Normal: boolean | null;

    BA01Misfit: boolean | null;
    BA02Misfit: boolean | null;
    BA03Misfit: boolean | null;
    BA04Misfit: boolean | null;
    BA05Misfit: boolean | null;
    BA06Misfit: boolean | null;
    BA07Misfit: boolean | null;
    BA08Misfit: boolean | null;
    BA09Misfit: boolean | null;
    BB01Misfit: boolean | null;
    BB02Misfit: boolean | null;
    BB03Misfit: boolean | null;
    BB04Misfit: boolean | null;
    BB05Misfit: boolean | null;
    BB06Misfit: boolean | null;
    BB07Misfit: boolean | null;
    BB08Misfit: boolean | null;
    BB09Misfit: boolean | null;
    BB10Misfit: boolean | null;
    BB11Misfit: boolean | null;
    BB12Misfit: boolean | null;
    BB13Misfit: boolean | null;
    BB14Misfit: boolean | null;
    BB15Misfit: boolean | null;
    BB16Misfit: boolean | null;
    BB17Misfit: boolean | null;
    BC01Misfit: boolean | null;
    BC02Misfit: boolean | null;
    BC03Misfit: boolean | null;
    BC04Misfit: boolean | null;
    BC05Misfit: boolean | null;
    BC06Misfit: boolean | null;
    BC07Misfit: boolean | null;
    BC08Misfit: boolean | null;
    BC09Misfit: boolean | null;
    BC10Misfit: boolean | null;
    BC11Misfit: boolean | null;
    BD01Misfit: boolean | null;
    BD02Misfit: boolean | null;
    BD03Misfit: boolean | null;
    BD04Misfit: boolean | null;
    BD05Misfit: boolean | null;
    BD06Misfit: boolean | null;
    BD07Misfit: boolean | null;
    BD08Misfit: boolean | null;
    BD09Misfit: boolean | null;
    BD10Misfit: boolean | null;
    BD11Misfit: boolean | null;
    BD12Misfit: boolean | null;
    BD13Misfit: boolean | null;
    BD14Misfit: boolean | null;
    BD15Misfit: boolean | null;
    BD16Misfit: boolean | null;
    BE01Misfit: boolean | null;
    BE02Misfit: boolean | null;
    BE03Misfit: boolean | null;
    BE04Misfit: boolean | null;
    BF01Misfit: boolean | null;
    BF02Misfit: boolean | null;
    BF03Misfit: boolean | null;
    BF04Misfit: boolean | null;
    BF05Misfit: boolean | null;
    BF06Misfit: boolean | null;
    BF07Misfit: boolean | null;
    BF08Misfit: boolean | null;
    BF09Misfit: boolean | null;
    BF10Misfit: boolean | null;
    BF11Misfit: boolean | null;
    BG01Misfit: boolean | null;
    BG02Misfit: boolean | null;
    BG03Misfit: boolean | null;
    BG04Misfit: boolean | null;
    BG05Misfit: boolean | null;
    BG06Misfit: boolean | null;
    BG07Misfit: boolean | null;
    BH01Misfit: boolean | null;
    BH02Misfit: boolean | null;
    BH03Misfit: boolean | null;
    BH04Misfit: boolean | null;
    BI01Misfit: boolean | null;
    BI02Misfit: boolean | null;
    BI03Misfit: boolean | null;
    BJ01Misfit: boolean | null;
    BJ02Misfit: boolean | null;
    BJ03Misfit: boolean | null;
    BJ04Misfit: boolean | null;
    BJ05Misfit: boolean | null;

    BA01Ameliorate: IEHSFormTargetInItem[];
    BA02Ameliorate: IEHSFormTargetInItem[];
    BA03Ameliorate: IEHSFormTargetInItem[];
    BA04Ameliorate: IEHSFormTargetInItem[];
    BA05Ameliorate: IEHSFormTargetInItem[];
    BA06Ameliorate: IEHSFormTargetInItem[];
    BA07Ameliorate: IEHSFormTargetInItem[];
    BA08Ameliorate: IEHSFormTargetInItem[];
    BA09Ameliorate: IEHSFormTargetInItem[];
    BB01Ameliorate: IEHSFormTargetInItem[];
    BB02Ameliorate: IEHSFormTargetInItem[];
    BB03Ameliorate: IEHSFormTargetInItem[];
    BB04Ameliorate: IEHSFormTargetInItem[];
    BB05Ameliorate: IEHSFormTargetInItem[];
    BB06Ameliorate: IEHSFormTargetInItem[];
    BB07Ameliorate: IEHSFormTargetInItem[];
    BB08Ameliorate: IEHSFormTargetInItem[];
    BB09Ameliorate: IEHSFormTargetInItem[];
    BB10Ameliorate: IEHSFormTargetInItem[];
    BB11Ameliorate: IEHSFormTargetInItem[];
    BB12Ameliorate: IEHSFormTargetInItem[];
    BB13Ameliorate: IEHSFormTargetInItem[];
    BB14Ameliorate: IEHSFormTargetInItem[];
    BB15Ameliorate: IEHSFormTargetInItem[];
    BB16Ameliorate: IEHSFormTargetInItem[];
    BB17Ameliorate: IEHSFormTargetInItem[];
    BC01Ameliorate: IEHSFormTargetInItem[];
    BC02Ameliorate: IEHSFormTargetInItem[];
    BC03Ameliorate: IEHSFormTargetInItem[];
    BC04Ameliorate: IEHSFormTargetInItem[];
    BC05Ameliorate: IEHSFormTargetInItem[];
    BC06Ameliorate: IEHSFormTargetInItem[];
    BC07Ameliorate: IEHSFormTargetInItem[];
    BC08Ameliorate: IEHSFormTargetInItem[];
    BC09Ameliorate: IEHSFormTargetInItem[];
    BC10Ameliorate: IEHSFormTargetInItem[];
    BC11Ameliorate: IEHSFormTargetInItem[];
    BD01Ameliorate: IEHSFormTargetInItem[];
    BD02Ameliorate: IEHSFormTargetInItem[];
    BD03Ameliorate: IEHSFormTargetInItem[];
    BD04Ameliorate: IEHSFormTargetInItem[];
    BD05Ameliorate: IEHSFormTargetInItem[];
    BD06Ameliorate: IEHSFormTargetInItem[];
    BD07Ameliorate: IEHSFormTargetInItem[];
    BD08Ameliorate: IEHSFormTargetInItem[];
    BD09Ameliorate: IEHSFormTargetInItem[];
    BD10Ameliorate: IEHSFormTargetInItem[];
    BD11Ameliorate: IEHSFormTargetInItem[];
    BD12Ameliorate: IEHSFormTargetInItem[];
    BD13Ameliorate: IEHSFormTargetInItem[];
    BD14Ameliorate: IEHSFormTargetInItem[];
    BD15Ameliorate: IEHSFormTargetInItem[];
    BD16Ameliorate: IEHSFormTargetInItem[];
    BE01Ameliorate: IEHSFormTargetInItem[];
    BE02Ameliorate: IEHSFormTargetInItem[];
    BE03Ameliorate: IEHSFormTargetInItem[];
    BE04Ameliorate: IEHSFormTargetInItem[];
    BF01Ameliorate: IEHSFormTargetInItem[];
    BF02Ameliorate: IEHSFormTargetInItem[];
    BF03Ameliorate: IEHSFormTargetInItem[];
    BF04Ameliorate: IEHSFormTargetInItem[];
    BF05Ameliorate: IEHSFormTargetInItem[];
    BF06Ameliorate: IEHSFormTargetInItem[];
    BF07Ameliorate: IEHSFormTargetInItem[];
    BF08Ameliorate: IEHSFormTargetInItem[];
    BF09Ameliorate: IEHSFormTargetInItem[];
    BF10Ameliorate: IEHSFormTargetInItem[];
    BF11Ameliorate: IEHSFormTargetInItem[];
    BG01Ameliorate: IEHSFormTargetInItem[];
    BG02Ameliorate: IEHSFormTargetInItem[];
    BG03Ameliorate: IEHSFormTargetInItem[];
    BG04Ameliorate: IEHSFormTargetInItem[];
    BG05Ameliorate: IEHSFormTargetInItem[];
    BG06Ameliorate: IEHSFormTargetInItem[];
    BG07Ameliorate: IEHSFormTargetInItem[];
    BH01Ameliorate: IEHSFormTargetInItem[];
    BH02Ameliorate: IEHSFormTargetInItem[];
    BH03Ameliorate: IEHSFormTargetInItem[];
    BH04Ameliorate: IEHSFormTargetInItem[];
    BI01Ameliorate: IEHSFormTargetInItem[];
    BI02Ameliorate: IEHSFormTargetInItem[];
    BI03Ameliorate: IEHSFormTargetInItem[];
    BJ01Ameliorate: IEHSFormTargetInItem[];
    BJ02Ameliorate: IEHSFormTargetInItem[];
    BJ03Ameliorate: IEHSFormTargetInItem[];
    BJ04Ameliorate: IEHSFormTargetInItem[];
    BJ05Ameliorate: IEHSFormTargetInItem[];
}

export type SpecialGroupKey =
    | 'BA'
    | 'BB'
    | 'BC'
    | 'BD'
    | 'BE'
    | 'BF'
    | 'BG'
    | 'BH'
    | 'BI'
    | 'BJ';
